# Generated by Django 6.1.1 on 2026-09-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Пусто — категория верхнего уровня.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category', verbose_name='Родительская категория'),
        ),
    ]
